services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: personalblog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: